/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.daos;


import com.dreamjob.db.jooq.tables.AdminActionLog;
import com.dreamjob.db.jooq.tables.records.AdminActionLogRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.JSONB;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class AdminActionLogDao extends DAOImpl<AdminActionLogRecord, com.dreamjob.db.jooq.tables.pojos.AdminActionLog, Integer> {

    /**
     * Create a new AdminActionLogDao without any configuration
     */
    public AdminActionLogDao() {
        super(AdminActionLog.ADMIN_ACTION_LOG, com.dreamjob.db.jooq.tables.pojos.AdminActionLog.class);
    }

    /**
     * Create a new AdminActionLogDao with an attached configuration
     */
    @Autowired
    public AdminActionLogDao(Configuration configuration) {
        super(AdminActionLog.ADMIN_ACTION_LOG, com.dreamjob.db.jooq.tables.pojos.AdminActionLog.class, configuration);
    }

    @Override
    public Integer getId(com.dreamjob.db.jooq.tables.pojos.AdminActionLog object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchById(Integer... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dreamjob.db.jooq.tables.pojos.AdminActionLog fetchOneById(Integer value) {
        return fetchOne(AdminActionLog.ADMIN_ACTION_LOG.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchOptionalById(Integer value) {
        return fetchOptional(AdminActionLog.ADMIN_ACTION_LOG.ID, value);
    }

    /**
     * Fetch records that have <code>admin_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfAdminId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.ADMIN_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>admin_id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByAdminId(Integer... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.ADMIN_ID, values);
    }

    /**
     * Fetch records that have <code>action_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfActionType(String lowerInclusive, String upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.ACTION_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>action_type IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByActionType(String... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.ACTION_TYPE, values);
    }

    /**
     * Fetch records that have <code>target_table BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfTargetTable(String lowerInclusive, String upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.TARGET_TABLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>target_table IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByTargetTable(String... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.TARGET_TABLE, values);
    }

    /**
     * Fetch records that have <code>record_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfRecordId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.RECORD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>record_id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByRecordId(Integer... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.RECORD_ID, values);
    }

    /**
     * Fetch records that have <code>change_details BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfChangeDetails(JSONB lowerInclusive, JSONB upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.CHANGE_DETAILS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>change_details IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByChangeDetails(JSONB... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.CHANGE_DETAILS, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchRangeOfCreatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(AdminActionLog.ADMIN_ACTION_LOG.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.AdminActionLog> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(AdminActionLog.ADMIN_ACTION_LOG.CREATED_ON, values);
    }
}
