/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.daos;


import com.dreamjob.db.jooq.tables.OfferResource;
import com.dreamjob.db.jooq.tables.records.OfferResourceRecord;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class OfferResourceDao extends DAOImpl<OfferResourceRecord, com.dreamjob.db.jooq.tables.pojos.OfferResource, Integer> {

    /**
     * Create a new OfferResourceDao without any configuration
     */
    public OfferResourceDao() {
        super(OfferResource.OFFER_RESOURCE, com.dreamjob.db.jooq.tables.pojos.OfferResource.class);
    }

    /**
     * Create a new OfferResourceDao with an attached configuration
     */
    @Autowired
    public OfferResourceDao(Configuration configuration) {
        super(OfferResource.OFFER_RESOURCE, com.dreamjob.db.jooq.tables.pojos.OfferResource.class, configuration);
    }

    @Override
    public Integer getId(com.dreamjob.db.jooq.tables.pojos.OfferResource object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchById(Integer... values) {
        return fetch(OfferResource.OFFER_RESOURCE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dreamjob.db.jooq.tables.pojos.OfferResource fetchOneById(Integer value) {
        return fetchOne(OfferResource.OFFER_RESOURCE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchOptionalById(Integer value) {
        return fetchOptional(OfferResource.OFFER_RESOURCE.ID, value);
    }

    /**
     * Fetch records that have <code>offer_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfOfferId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.OFFER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>offer_id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByOfferId(Integer... values) {
        return fetch(OfferResource.OFFER_RESOURCE.OFFER_ID, values);
    }

    /**
     * Fetch records that have <code>resource_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfResourceId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.RESOURCE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>resource_id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByResourceId(Integer... values) {
        return fetch(OfferResource.OFFER_RESOURCE.RESOURCE_ID, values);
    }

    /**
     * Fetch records that have <code>quantity BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfQuantity(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.QUANTITY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>quantity IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByQuantity(BigDecimal... values) {
        return fetch(OfferResource.OFFER_RESOURCE.QUANTITY, values);
    }

    /**
     * Fetch records that have <code>unit_price BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfUnitPrice(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.UNIT_PRICE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>unit_price IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByUnitPrice(BigDecimal... values) {
        return fetch(OfferResource.OFFER_RESOURCE.UNIT_PRICE, values);
    }

    /**
     * Fetch records that have <code>total_cost BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfTotalCost(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.TOTAL_COST, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>total_cost IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByTotalCost(BigDecimal... values) {
        return fetch(OfferResource.OFFER_RESOURCE.TOTAL_COST, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfCreatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(OfferResource.OFFER_RESOURCE.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchRangeOfUpdatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(OfferResource.OFFER_RESOURCE.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.OfferResource> fetchByUpdatedOn(LocalDateTime... values) {
        return fetch(OfferResource.OFFER_RESOURCE.UPDATED_ON, values);
    }
}
