/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.daos;


import com.dreamjob.db.jooq.tables.ProfessionType;
import com.dreamjob.db.jooq.tables.records.ProfessionTypeRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class ProfessionTypeDao extends DAOImpl<ProfessionTypeRecord, com.dreamjob.db.jooq.tables.pojos.ProfessionType, Integer> {

    /**
     * Create a new ProfessionTypeDao without any configuration
     */
    public ProfessionTypeDao() {
        super(ProfessionType.PROFESSION_TYPE, com.dreamjob.db.jooq.tables.pojos.ProfessionType.class);
    }

    /**
     * Create a new ProfessionTypeDao with an attached configuration
     */
    @Autowired
    public ProfessionTypeDao(Configuration configuration) {
        super(ProfessionType.PROFESSION_TYPE, com.dreamjob.db.jooq.tables.pojos.ProfessionType.class, configuration);
    }

    @Override
    public Integer getId(com.dreamjob.db.jooq.tables.pojos.ProfessionType object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(ProfessionType.PROFESSION_TYPE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchById(Integer... values) {
        return fetch(ProfessionType.PROFESSION_TYPE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dreamjob.db.jooq.tables.pojos.ProfessionType fetchOneById(Integer value) {
        return fetchOne(ProfessionType.PROFESSION_TYPE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchOptionalById(Integer value) {
        return fetchOptional(ProfessionType.PROFESSION_TYPE.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProfessionType.PROFESSION_TYPE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchByName(String... values) {
        return fetch(ProfessionType.PROFESSION_TYPE.NAME, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(ProfessionType.PROFESSION_TYPE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchByDescription(String... values) {
        return fetch(ProfessionType.PROFESSION_TYPE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchRangeOfCreatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProfessionType.PROFESSION_TYPE.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(ProfessionType.PROFESSION_TYPE.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchRangeOfUpdatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ProfessionType.PROFESSION_TYPE.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.ProfessionType> fetchByUpdatedOn(LocalDateTime... values) {
        return fetch(ProfessionType.PROFESSION_TYPE.UPDATED_ON, values);
    }
}
