/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.daos;


import com.dreamjob.db.jooq.tables.TraderDetails;
import com.dreamjob.db.jooq.tables.records.TraderDetailsRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import javax.annotation.processing.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class TraderDetailsDao extends DAOImpl<TraderDetailsRecord, com.dreamjob.db.jooq.tables.pojos.TraderDetails, Integer> {

    /**
     * Create a new TraderDetailsDao without any configuration
     */
    public TraderDetailsDao() {
        super(TraderDetails.TRADER_DETAILS, com.dreamjob.db.jooq.tables.pojos.TraderDetails.class);
    }

    /**
     * Create a new TraderDetailsDao with an attached configuration
     */
    @Autowired
    public TraderDetailsDao(Configuration configuration) {
        super(TraderDetails.TRADER_DETAILS, com.dreamjob.db.jooq.tables.pojos.TraderDetails.class, configuration);
    }

    @Override
    public Integer getId(com.dreamjob.db.jooq.tables.pojos.TraderDetails object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchById(Integer... values) {
        return fetch(TraderDetails.TRADER_DETAILS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.dreamjob.db.jooq.tables.pojos.TraderDetails fetchOneById(Integer value) {
        return fetchOne(TraderDetails.TRADER_DETAILS.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchOptionalById(Integer value) {
        return fetchOptional(TraderDetails.TRADER_DETAILS.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfUserId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByUserId(Integer... values) {
        return fetch(TraderDetails.TRADER_DETAILS.USER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public com.dreamjob.db.jooq.tables.pojos.TraderDetails fetchOneByUserId(Integer value) {
        return fetchOne(TraderDetails.TRADER_DETAILS.USER_ID, value);
    }

    /**
     * Fetch a unique record that has <code>user_id = value</code>
     */
    public Optional<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchOptionalByUserId(Integer value) {
        return fetchOptional(TraderDetails.TRADER_DETAILS.USER_ID, value);
    }

    /**
     * Fetch records that have <code>mobile_number BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfMobileNumber(String lowerInclusive, String upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.MOBILE_NUMBER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>mobile_number IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByMobileNumber(String... values) {
        return fetch(TraderDetails.TRADER_DETAILS.MOBILE_NUMBER, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByDescription(String... values) {
        return fetch(TraderDetails.TRADER_DETAILS.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfStatus(String lowerInclusive, String upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.STATUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByStatus(String... values) {
        return fetch(TraderDetails.TRADER_DETAILS.STATUS, values);
    }

    /**
     * Fetch records that have <code>created_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfCreatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.CREATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByCreatedOn(LocalDateTime... values) {
        return fetch(TraderDetails.TRADER_DETAILS.CREATED_ON, values);
    }

    /**
     * Fetch records that have <code>updated_on BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchRangeOfUpdatedOn(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(TraderDetails.TRADER_DETAILS.UPDATED_ON, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>updated_on IN (values)</code>
     */
    public List<com.dreamjob.db.jooq.tables.pojos.TraderDetails> fetchByUpdatedOn(LocalDateTime... values) {
        return fetch(TraderDetails.TRADER_DETAILS.UPDATED_ON, values);
    }
}
