/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.AdminActionLog;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminActionLogRecord extends UpdatableRecordImpl<AdminActionLogRecord> implements Record7<Integer, Integer, String, String, Integer, JSONB, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>admin_action_log.id</code>.
     */
    public AdminActionLogRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>admin_action_log.admin_id</code>.
     */
    public AdminActionLogRecord setAdminId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.admin_id</code>.
     */
    public Integer getAdminId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>admin_action_log.action_type</code>.
     */
    public AdminActionLogRecord setActionType(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.action_type</code>.
     */
    public String getActionType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>admin_action_log.target_table</code>.
     */
    public AdminActionLogRecord setTargetTable(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.target_table</code>.
     */
    public String getTargetTable() {
        return (String) get(3);
    }

    /**
     * Setter for <code>admin_action_log.record_id</code>.
     */
    public AdminActionLogRecord setRecordId(Integer value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.record_id</code>.
     */
    public Integer getRecordId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>admin_action_log.change_details</code>.
     */
    public AdminActionLogRecord setChangeDetails(JSONB value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.change_details</code>.
     */
    public JSONB getChangeDetails() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>admin_action_log.created_on</code>.
     */
    public AdminActionLogRecord setCreatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>admin_action_log.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, String, Integer, JSONB, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, String, Integer, JSONB, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AdminActionLog.ADMIN_ACTION_LOG.ID;
    }

    @Override
    public Field<Integer> field2() {
        return AdminActionLog.ADMIN_ACTION_LOG.ADMIN_ID;
    }

    @Override
    public Field<String> field3() {
        return AdminActionLog.ADMIN_ACTION_LOG.ACTION_TYPE;
    }

    @Override
    public Field<String> field4() {
        return AdminActionLog.ADMIN_ACTION_LOG.TARGET_TABLE;
    }

    @Override
    public Field<Integer> field5() {
        return AdminActionLog.ADMIN_ACTION_LOG.RECORD_ID;
    }

    @Override
    public Field<JSONB> field6() {
        return AdminActionLog.ADMIN_ACTION_LOG.CHANGE_DETAILS;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return AdminActionLog.ADMIN_ACTION_LOG.CREATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getAdminId();
    }

    @Override
    public String component3() {
        return getActionType();
    }

    @Override
    public String component4() {
        return getTargetTable();
    }

    @Override
    public Integer component5() {
        return getRecordId();
    }

    @Override
    public JSONB component6() {
        return getChangeDetails();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getAdminId();
    }

    @Override
    public String value3() {
        return getActionType();
    }

    @Override
    public String value4() {
        return getTargetTable();
    }

    @Override
    public Integer value5() {
        return getRecordId();
    }

    @Override
    public JSONB value6() {
        return getChangeDetails();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedOn();
    }

    @Override
    public AdminActionLogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value2(Integer value) {
        setAdminId(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value3(String value) {
        setActionType(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value4(String value) {
        setTargetTable(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value5(Integer value) {
        setRecordId(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value6(JSONB value) {
        setChangeDetails(value);
        return this;
    }

    @Override
    public AdminActionLogRecord value7(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public AdminActionLogRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, JSONB value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminActionLogRecord
     */
    public AdminActionLogRecord() {
        super(AdminActionLog.ADMIN_ACTION_LOG);
    }

    /**
     * Create a detached, initialised AdminActionLogRecord
     */
    @ConstructorProperties({ "id", "adminId", "actionType", "targetTable", "recordId", "changeDetails", "createdOn" })
    public AdminActionLogRecord(Integer id, Integer adminId, String actionType, String targetTable, Integer recordId, JSONB changeDetails, LocalDateTime createdOn) {
        super(AdminActionLog.ADMIN_ACTION_LOG);

        setId(id);
        setAdminId(adminId);
        setActionType(actionType);
        setTargetTable(targetTable);
        setRecordId(recordId);
        setChangeDetails(changeDetails);
        setCreatedOn(createdOn);
    }

    /**
     * Create a detached, initialised AdminActionLogRecord
     */
    @ConstructorProperties({ "id", "adminId", "actionType", "targetTable", "recordId", "changeDetails", "createdOn" })
    public AdminActionLogRecord(com.dreamjob.db.jooq.tables.pojos.AdminActionLog value) {
        super(AdminActionLog.ADMIN_ACTION_LOG);

        if (value != null) {
            setId(value.getId());
            setAdminId(value.getAdminId());
            setActionType(value.getActionType());
            setTargetTable(value.getTargetTable());
            setRecordId(value.getRecordId());
            setChangeDetails(value.getChangeDetails());
            setCreatedOn(value.getCreatedOn());
        }
    }
}
