/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.Administrator;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdministratorRecord extends UpdatableRecordImpl<AdministratorRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>administrator.id</code>.
     */
    public AdministratorRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>administrator.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>administrator.username</code>.
     */
    public AdministratorRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>administrator.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>administrator.email</code>.
     */
    public AdministratorRecord setEmail(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>administrator.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>administrator.password</code>.
     */
    public AdministratorRecord setPassword(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>administrator.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>administrator.created_on</code>.
     */
    public AdministratorRecord setCreatedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>administrator.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>administrator.updated_on</code>.
     */
    public AdministratorRecord setUpdatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>administrator.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Administrator.ADMINISTRATOR.ID;
    }

    @Override
    public Field<String> field2() {
        return Administrator.ADMINISTRATOR.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Administrator.ADMINISTRATOR.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return Administrator.ADMINISTRATOR.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Administrator.ADMINISTRATOR.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Administrator.ADMINISTRATOR.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedOn();
    }

    @Override
    public AdministratorRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AdministratorRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AdministratorRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AdministratorRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public AdministratorRecord value5(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public AdministratorRecord value6(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public AdministratorRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdministratorRecord
     */
    public AdministratorRecord() {
        super(Administrator.ADMINISTRATOR);
    }

    /**
     * Create a detached, initialised AdministratorRecord
     */
    @ConstructorProperties({ "id", "username", "email", "password", "createdOn", "updatedOn" })
    public AdministratorRecord(Integer id, String username, String email, String password, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(Administrator.ADMINISTRATOR);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPassword(password);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised AdministratorRecord
     */
    @ConstructorProperties({ "id", "username", "email", "password", "createdOn", "updatedOn" })
    public AdministratorRecord(com.dreamjob.db.jooq.tables.pojos.Administrator value) {
        super(Administrator.ADMINISTRATOR);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setEmail(value.getEmail());
            setPassword(value.getPassword());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
