/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.City;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityRecord extends UpdatableRecordImpl<CityRecord> implements Record5<Integer, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>city.id</code>.
     */
    public CityRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>city.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>city.city_name</code>.
     */
    public CityRecord setCityName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>city.city_name</code>.
     */
    public String getCityName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>city.status</code>.
     */
    public CityRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>city.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>city.created_on</code>.
     */
    public CityRecord setCreatedOn(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>city.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>city.updated_on</code>.
     */
    public CityRecord setUpdatedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>city.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return City.CITY.ID;
    }

    @Override
    public Field<String> field2() {
        return City.CITY.CITY_NAME;
    }

    @Override
    public Field<String> field3() {
        return City.CITY.STATUS;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return City.CITY.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return City.CITY.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getCityName();
    }

    @Override
    public String component3() {
        return getStatus();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getCityName();
    }

    @Override
    public String value3() {
        return getStatus();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedOn();
    }

    @Override
    public CityRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CityRecord value2(String value) {
        setCityName(value);
        return this;
    }

    @Override
    public CityRecord value3(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public CityRecord value4(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public CityRecord value5(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public CityRecord values(Integer value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CityRecord
     */
    public CityRecord() {
        super(City.CITY);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    @ConstructorProperties({ "id", "cityName", "status", "createdOn", "updatedOn" })
    public CityRecord(Integer id, String cityName, String status, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(City.CITY);

        setId(id);
        setCityName(cityName);
        setStatus(status);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised CityRecord
     */
    @ConstructorProperties({ "id", "cityName", "status", "createdOn", "updatedOn" })
    public CityRecord(com.dreamjob.db.jooq.tables.pojos.City value) {
        super(City.CITY);

        if (value != null) {
            setId(value.getId());
            setCityName(value.getCityName());
            setStatus(value.getStatus());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
