/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.OfferResource;

import java.beans.ConstructorProperties;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OfferResourceRecord extends UpdatableRecordImpl<OfferResourceRecord> implements Record8<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>offer_resource.id</code>.
     */
    public OfferResourceRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>offer_resource.offer_id</code>.
     */
    public OfferResourceRecord setOfferId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.offer_id</code>.
     */
    public Integer getOfferId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>offer_resource.resource_id</code>.
     */
    public OfferResourceRecord setResourceId(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.resource_id</code>.
     */
    public Integer getResourceId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>offer_resource.quantity</code>.
     */
    public OfferResourceRecord setQuantity(BigDecimal value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>offer_resource.unit_price</code>.
     */
    public OfferResourceRecord setUnitPrice(BigDecimal value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>offer_resource.total_cost</code>.
     */
    public OfferResourceRecord setTotalCost(BigDecimal value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.total_cost</code>.
     */
    public BigDecimal getTotalCost() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>offer_resource.created_on</code>.
     */
    public OfferResourceRecord setCreatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>offer_resource.updated_on</code>.
     */
    public OfferResourceRecord setUpdatedOn(LocalDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>offer_resource.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return OfferResource.OFFER_RESOURCE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return OfferResource.OFFER_RESOURCE.OFFER_ID;
    }

    @Override
    public Field<Integer> field3() {
        return OfferResource.OFFER_RESOURCE.RESOURCE_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return OfferResource.OFFER_RESOURCE.QUANTITY;
    }

    @Override
    public Field<BigDecimal> field5() {
        return OfferResource.OFFER_RESOURCE.UNIT_PRICE;
    }

    @Override
    public Field<BigDecimal> field6() {
        return OfferResource.OFFER_RESOURCE.TOTAL_COST;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return OfferResource.OFFER_RESOURCE.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return OfferResource.OFFER_RESOURCE.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getOfferId();
    }

    @Override
    public Integer component3() {
        return getResourceId();
    }

    @Override
    public BigDecimal component4() {
        return getQuantity();
    }

    @Override
    public BigDecimal component5() {
        return getUnitPrice();
    }

    @Override
    public BigDecimal component6() {
        return getTotalCost();
    }

    @Override
    public LocalDateTime component7() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component8() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getOfferId();
    }

    @Override
    public Integer value3() {
        return getResourceId();
    }

    @Override
    public BigDecimal value4() {
        return getQuantity();
    }

    @Override
    public BigDecimal value5() {
        return getUnitPrice();
    }

    @Override
    public BigDecimal value6() {
        return getTotalCost();
    }

    @Override
    public LocalDateTime value7() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value8() {
        return getUpdatedOn();
    }

    @Override
    public OfferResourceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public OfferResourceRecord value2(Integer value) {
        setOfferId(value);
        return this;
    }

    @Override
    public OfferResourceRecord value3(Integer value) {
        setResourceId(value);
        return this;
    }

    @Override
    public OfferResourceRecord value4(BigDecimal value) {
        setQuantity(value);
        return this;
    }

    @Override
    public OfferResourceRecord value5(BigDecimal value) {
        setUnitPrice(value);
        return this;
    }

    @Override
    public OfferResourceRecord value6(BigDecimal value) {
        setTotalCost(value);
        return this;
    }

    @Override
    public OfferResourceRecord value7(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public OfferResourceRecord value8(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public OfferResourceRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OfferResourceRecord
     */
    public OfferResourceRecord() {
        super(OfferResource.OFFER_RESOURCE);
    }

    /**
     * Create a detached, initialised OfferResourceRecord
     */
    @ConstructorProperties({ "id", "offerId", "resourceId", "quantity", "unitPrice", "totalCost", "createdOn", "updatedOn" })
    public OfferResourceRecord(Integer id, Integer offerId, Integer resourceId, BigDecimal quantity, BigDecimal unitPrice, BigDecimal totalCost, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(OfferResource.OFFER_RESOURCE);

        setId(id);
        setOfferId(offerId);
        setResourceId(resourceId);
        setQuantity(quantity);
        setUnitPrice(unitPrice);
        setTotalCost(totalCost);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised OfferResourceRecord
     */
    @ConstructorProperties({ "id", "offerId", "resourceId", "quantity", "unitPrice", "totalCost", "createdOn", "updatedOn" })
    public OfferResourceRecord(com.dreamjob.db.jooq.tables.pojos.OfferResource value) {
        super(OfferResource.OFFER_RESOURCE);

        if (value != null) {
            setId(value.getId());
            setOfferId(value.getOfferId());
            setResourceId(value.getResourceId());
            setQuantity(value.getQuantity());
            setUnitPrice(value.getUnitPrice());
            setTotalCost(value.getTotalCost());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
