/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.Profession;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessionRecord extends UpdatableRecordImpl<ProfessionRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>profession.id</code>.
     */
    public ProfessionRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>profession.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>profession.profession_name</code>.
     */
    public ProfessionRecord setProfessionName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>profession.profession_name</code>.
     */
    public String getProfessionName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>profession.description</code>.
     */
    public ProfessionRecord setDescription(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>profession.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>profession.status</code>.
     */
    public ProfessionRecord setStatus(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>profession.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>profession.created_on</code>.
     */
    public ProfessionRecord setCreatedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>profession.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>profession.updated_on</code>.
     */
    public ProfessionRecord setUpdatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>profession.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Profession.PROFESSION.ID;
    }

    @Override
    public Field<String> field2() {
        return Profession.PROFESSION.PROFESSION_NAME;
    }

    @Override
    public Field<String> field3() {
        return Profession.PROFESSION.DESCRIPTION;
    }

    @Override
    public Field<String> field4() {
        return Profession.PROFESSION.STATUS;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Profession.PROFESSION.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Profession.PROFESSION.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getProfessionName();
    }

    @Override
    public String component3() {
        return getDescription();
    }

    @Override
    public String component4() {
        return getStatus();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getProfessionName();
    }

    @Override
    public String value3() {
        return getDescription();
    }

    @Override
    public String value4() {
        return getStatus();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedOn();
    }

    @Override
    public ProfessionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ProfessionRecord value2(String value) {
        setProfessionName(value);
        return this;
    }

    @Override
    public ProfessionRecord value3(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ProfessionRecord value4(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public ProfessionRecord value5(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public ProfessionRecord value6(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public ProfessionRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfessionRecord
     */
    public ProfessionRecord() {
        super(Profession.PROFESSION);
    }

    /**
     * Create a detached, initialised ProfessionRecord
     */
    @ConstructorProperties({ "id", "professionName", "description", "status", "createdOn", "updatedOn" })
    public ProfessionRecord(Integer id, String professionName, String description, String status, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(Profession.PROFESSION);

        setId(id);
        setProfessionName(professionName);
        setDescription(description);
        setStatus(status);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised ProfessionRecord
     */
    @ConstructorProperties({ "id", "professionName", "description", "status", "createdOn", "updatedOn" })
    public ProfessionRecord(com.dreamjob.db.jooq.tables.pojos.Profession value) {
        super(Profession.PROFESSION);

        if (value != null) {
            setId(value.getId());
            setProfessionName(value.getProfessionName());
            setDescription(value.getDescription());
            setStatus(value.getStatus());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
