/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.TraderDetails;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraderDetailsRecord extends UpdatableRecordImpl<TraderDetailsRecord> implements Record7<Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>trader_details.id</code>.
     */
    public TraderDetailsRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>trader_details.user_id</code>.
     */
    public TraderDetailsRecord setUserId(Integer value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>trader_details.mobile_number</code>.
     */
    public TraderDetailsRecord setMobileNumber(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.mobile_number</code>.
     */
    public String getMobileNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>trader_details.description</code>.
     */
    public TraderDetailsRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>trader_details.status</code>.
     */
    public TraderDetailsRecord setStatus(String value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.status</code>.
     */
    public String getStatus() {
        return (String) get(4);
    }

    /**
     * Setter for <code>trader_details.created_on</code>.
     */
    public TraderDetailsRecord setCreatedOn(LocalDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>trader_details.updated_on</code>.
     */
    public TraderDetailsRecord setUpdatedOn(LocalDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>trader_details.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return TraderDetails.TRADER_DETAILS.ID;
    }

    @Override
    public Field<Integer> field2() {
        return TraderDetails.TRADER_DETAILS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return TraderDetails.TRADER_DETAILS.MOBILE_NUMBER;
    }

    @Override
    public Field<String> field4() {
        return TraderDetails.TRADER_DETAILS.DESCRIPTION;
    }

    @Override
    public Field<String> field5() {
        return TraderDetails.TRADER_DETAILS.STATUS;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TraderDetails.TRADER_DETAILS.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TraderDetails.TRADER_DETAILS.UPDATED_ON;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getMobileNumber();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public String component5() {
        return getStatus();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component7() {
        return getUpdatedOn();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getMobileNumber();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public String value5() {
        return getStatus();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value7() {
        return getUpdatedOn();
    }

    @Override
    public TraderDetailsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value3(String value) {
        setMobileNumber(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value5(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value6(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public TraderDetailsRecord value7(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public TraderDetailsRecord values(Integer value1, Integer value2, String value3, String value4, String value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TraderDetailsRecord
     */
    public TraderDetailsRecord() {
        super(TraderDetails.TRADER_DETAILS);
    }

    /**
     * Create a detached, initialised TraderDetailsRecord
     */
    @ConstructorProperties({ "id", "userId", "mobileNumber", "description", "status", "createdOn", "updatedOn" })
    public TraderDetailsRecord(Integer id, Integer userId, String mobileNumber, String description, String status, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(TraderDetails.TRADER_DETAILS);

        setId(id);
        setUserId(userId);
        setMobileNumber(mobileNumber);
        setDescription(description);
        setStatus(status);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised TraderDetailsRecord
     */
    @ConstructorProperties({ "id", "userId", "mobileNumber", "description", "status", "createdOn", "updatedOn" })
    public TraderDetailsRecord(com.dreamjob.db.jooq.tables.pojos.TraderDetails value) {
        super(TraderDetails.TRADER_DETAILS);

        if (value != null) {
            setId(value.getId());
            setUserId(value.getUserId());
            setMobileNumber(value.getMobileNumber());
            setDescription(value.getDescription());
            setStatus(value.getStatus());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
