/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.records;


import com.dreamjob.db.jooq.tables.UserDetails;

import java.beans.ConstructorProperties;
import java.time.LocalDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDetailsRecord extends UpdatableRecordImpl<UserDetailsRecord> implements Record5<UUID, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_details.id</code>.
     */
    public UserDetailsRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>user_details.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>user_details.username</code>.
     */
    public UserDetailsRecord setUsername(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>user_details.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_details.password</code>.
     */
    public UserDetailsRecord setPassword(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>user_details.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_details.created_on</code>.
     */
    public UserDetailsRecord setCreatedOn(LocalDateTime value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>user_details.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>user_details.updated_on</code>.
     */
    public UserDetailsRecord setUpdatedOn(LocalDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>user_details.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return UserDetails.USER_DETAILS.ID;
    }

    @Override
    public Field<String> field2() {
        return UserDetails.USER_DETAILS.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return UserDetails.USER_DETAILS.PASSWORD;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return UserDetails.USER_DETAILS.CREATED_ON;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return UserDetails.USER_DETAILS.UPDATED_ON;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public LocalDateTime component4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime component5() {
        return getUpdatedOn();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public LocalDateTime value4() {
        return getCreatedOn();
    }

    @Override
    public LocalDateTime value5() {
        return getUpdatedOn();
    }

    @Override
    public UserDetailsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UserDetailsRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UserDetailsRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserDetailsRecord value4(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public UserDetailsRecord value5(LocalDateTime value) {
        setUpdatedOn(value);
        return this;
    }

    @Override
    public UserDetailsRecord values(UUID value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDetailsRecord
     */
    public UserDetailsRecord() {
        super(UserDetails.USER_DETAILS);
    }

    /**
     * Create a detached, initialised UserDetailsRecord
     */
    @ConstructorProperties({ "id", "username", "password", "createdOn", "updatedOn" })
    public UserDetailsRecord(UUID id, String username, String password, LocalDateTime createdOn, LocalDateTime updatedOn) {
        super(UserDetails.USER_DETAILS);

        setId(id);
        setUsername(username);
        setPassword(password);
        setCreatedOn(createdOn);
        setUpdatedOn(updatedOn);
    }

    /**
     * Create a detached, initialised UserDetailsRecord
     */
    @ConstructorProperties({ "id", "username", "password", "createdOn", "updatedOn" })
    public UserDetailsRecord(com.dreamjob.db.jooq.tables.pojos.UserDetails value) {
        super(UserDetails.USER_DETAILS);

        if (value != null) {
            setId(value.getId());
            setUsername(value.getUsername());
            setPassword(value.getPassword());
            setCreatedOn(value.getCreatedOn());
            setUpdatedOn(value.getUpdatedOn());
        }
    }
}
