/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables;


import com.dreamjob.db.jooq.DefaultSchema;
import com.dreamjob.db.jooq.Keys;
import com.dreamjob.db.jooq.tables.records.ProfessionTypeRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessionType extends TableImpl<ProfessionTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>profession_type</code>
     */
    public static final ProfessionType PROFESSION_TYPE = new ProfessionType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessionTypeRecord> getRecordType() {
        return ProfessionTypeRecord.class;
    }

    /**
     * The column <code>profession_type.id</code>.
     */
    public final TableField<ProfessionTypeRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>profession_type.name</code>.
     */
    public final TableField<ProfessionTypeRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>profession_type.description</code>.
     */
    public final TableField<ProfessionTypeRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>profession_type.created_on</code>.
     */
    public final TableField<ProfessionTypeRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>profession_type.updated_on</code>.
     */
    public final TableField<ProfessionTypeRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private ProfessionType(Name alias, Table<ProfessionTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProfessionType(Name alias, Table<ProfessionTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>profession_type</code> table reference
     */
    public ProfessionType(String alias) {
        this(DSL.name(alias), PROFESSION_TYPE);
    }

    /**
     * Create an aliased <code>profession_type</code> table reference
     */
    public ProfessionType(Name alias) {
        this(alias, PROFESSION_TYPE);
    }

    /**
     * Create a <code>profession_type</code> table reference
     */
    public ProfessionType() {
        this(DSL.name("profession_type"), null);
    }

    public <O extends Record> ProfessionType(Table<O> child, ForeignKey<O, ProfessionTypeRecord> key) {
        super(child, key, PROFESSION_TYPE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ProfessionTypeRecord, Integer> getIdentity() {
        return (Identity<ProfessionTypeRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ProfessionTypeRecord> getPrimaryKey() {
        return Keys.PROFESSION_TYPE_PKEY;
    }

    @Override
    public ProfessionType as(String alias) {
        return new ProfessionType(DSL.name(alias), this);
    }

    @Override
    public ProfessionType as(Name alias) {
        return new ProfessionType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProfessionType rename(String name) {
        return new ProfessionType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProfessionType rename(Name name) {
        return new ProfessionType(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
