/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables;


import com.dreamjob.db.jooq.DefaultSchema;
import com.dreamjob.db.jooq.Keys;
import com.dreamjob.db.jooq.tables.records.ResourceRecord;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Resource extends TableImpl<ResourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>resource</code>
     */
    public static final Resource RESOURCE = new Resource();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ResourceRecord> getRecordType() {
        return ResourceRecord.class;
    }

    /**
     * The column <code>resource.id</code>.
     */
    public final TableField<ResourceRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>resource.name</code>.
     */
    public final TableField<ResourceRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>resource.unit</code>.
     */
    public final TableField<ResourceRecord, String> UNIT = createField(DSL.name("unit"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>resource.created_on</code>.
     */
    public final TableField<ResourceRecord, LocalDateTime> CREATED_ON = createField(DSL.name("created_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    /**
     * The column <code>resource.updated_on</code>.
     */
    public final TableField<ResourceRecord, LocalDateTime> UPDATED_ON = createField(DSL.name("updated_on"), SQLDataType.LOCALDATETIME(3).nullable(false), this, "");

    private Resource(Name alias, Table<ResourceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Resource(Name alias, Table<ResourceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>resource</code> table reference
     */
    public Resource(String alias) {
        this(DSL.name(alias), RESOURCE);
    }

    /**
     * Create an aliased <code>resource</code> table reference
     */
    public Resource(Name alias) {
        this(alias, RESOURCE);
    }

    /**
     * Create a <code>resource</code> table reference
     */
    public Resource() {
        this(DSL.name("resource"), null);
    }

    public <O extends Record> Resource(Table<O> child, ForeignKey<O, ResourceRecord> key) {
        super(child, key, RESOURCE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<ResourceRecord, Integer> getIdentity() {
        return (Identity<ResourceRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ResourceRecord> getPrimaryKey() {
        return Keys.RESOURCE_PKEY;
    }

    @Override
    public Resource as(String alias) {
        return new Resource(DSL.name(alias), this);
    }

    @Override
    public Resource as(Name alias) {
        return new Resource(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Resource rename(String name) {
        return new Resource(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Resource rename(Name name) {
        return new Resource(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
