/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq;


import com.dreamjob.db.jooq.tables.AdminActionLog;
import com.dreamjob.db.jooq.tables.Administrator;
import com.dreamjob.db.jooq.tables.City;
import com.dreamjob.db.jooq.tables.Offer;
import com.dreamjob.db.jooq.tables.Profession;
import com.dreamjob.db.jooq.tables.TraderDetails;
import com.dreamjob.db.jooq.tables.TraderDetailsProfession;
import com.dreamjob.db.jooq.tables.UserDetails;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>admin_action_log</code>.
     */
    public final AdminActionLog ADMIN_ACTION_LOG = AdminActionLog.ADMIN_ACTION_LOG;

    /**
     * The table <code>administrator</code>.
     */
    public final Administrator ADMINISTRATOR = Administrator.ADMINISTRATOR;

    /**
     * The table <code>city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>offer</code>.
     */
    public final Offer OFFER = Offer.OFFER;

    /**
     * The table <code>profession</code>.
     */
    public final Profession PROFESSION = Profession.PROFESSION;

    /**
     * The table <code>trader_details</code>.
     */
    public final TraderDetails TRADER_DETAILS = TraderDetails.TRADER_DETAILS;

    /**
     * The table <code>trader_details_profession</code>.
     */
    public final TraderDetailsProfession TRADER_DETAILS_PROFESSION = TraderDetailsProfession.TRADER_DETAILS_PROFESSION;

    /**
     * The table <code>user_details</code>.
     */
    public final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            AdminActionLog.ADMIN_ACTION_LOG,
            Administrator.ADMINISTRATOR,
            City.CITY,
            Offer.OFFER,
            Profession.PROFESSION,
            TraderDetails.TRADER_DETAILS,
            TraderDetailsProfession.TRADER_DETAILS_PROFESSION,
            UserDetails.USER_DETAILS
        );
    }
}
