/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq;


import com.dreamjob.db.jooq.tables.Offer;
import com.dreamjob.db.jooq.tables.OfferResource;
import com.dreamjob.db.jooq.tables.ProfessionType;
import com.dreamjob.db.jooq.tables.Resource;
import com.dreamjob.db.jooq.tables.TraderDetails;
import com.dreamjob.db.jooq.tables.UserDetails;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>offer</code>.
     */
    public final Offer OFFER = Offer.OFFER;

    /**
     * The table <code>offer_resource</code>.
     */
    public final OfferResource OFFER_RESOURCE = OfferResource.OFFER_RESOURCE;

    /**
     * The table <code>profession_type</code>.
     */
    public final ProfessionType PROFESSION_TYPE = ProfessionType.PROFESSION_TYPE;

    /**
     * The table <code>resource</code>.
     */
    public final Resource RESOURCE = Resource.RESOURCE;

    /**
     * The table <code>trader_details</code>.
     */
    public final TraderDetails TRADER_DETAILS = TraderDetails.TRADER_DETAILS;

    /**
     * The table <code>user_details</code>.
     */
    public final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Offer.OFFER,
            OfferResource.OFFER_RESOURCE,
            ProfessionType.PROFESSION_TYPE,
            Resource.RESOURCE,
            TraderDetails.TRADER_DETAILS,
            UserDetails.USER_DETAILS
        );
    }
}
