/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq;


import com.dreamjob.db.jooq.tables.TraderDetails;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TRADER_DETAILS_PROFESSION_TYPE_ID = Internal.createIndex(DSL.name("idx_trader_details_profession_type_id"), TraderDetails.TRADER_DETAILS, new OrderField[] { TraderDetails.TRADER_DETAILS.PROFESSION_ID }, false);
    public static final Index IDX_TRADER_DETAILS_USER_DETAILS_ID = Internal.createIndex(DSL.name("idx_trader_details_user_details_id"), TraderDetails.TRADER_DETAILS, new OrderField[] { TraderDetails.TRADER_DETAILS.USER_ID }, false);
}
