/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq;


import com.dreamjob.db.jooq.tables.UserDetails;
import com.dreamjob.db.jooq.tables.records.UserDetailsRecord;

import javax.annotation.processing.Generated;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserDetailsRecord> USER_DETAILS_PKEY = Internal.createUniqueKey(UserDetails.USER_DETAILS, DSL.name("user_details_pkey"), new TableField[] { UserDetails.USER_DETAILS.ID }, true);
    public static final UniqueKey<UserDetailsRecord> USER_DETAILS_USERNAME_KEY = Internal.createUniqueKey(UserDetails.USER_DETAILS, DSL.name("user_details_username_key"), new TableField[] { UserDetails.USER_DETAILS.USERNAME }, true);
}
