/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq;


import com.dreamjob.db.jooq.tables.AdminActionLog;
import com.dreamjob.db.jooq.tables.Administrator;
import com.dreamjob.db.jooq.tables.City;
import com.dreamjob.db.jooq.tables.Offer;
import com.dreamjob.db.jooq.tables.Profession;
import com.dreamjob.db.jooq.tables.TraderDetails;
import com.dreamjob.db.jooq.tables.TraderDetailsProfession;
import com.dreamjob.db.jooq.tables.UserDetails;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in the default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>admin_action_log</code>.
     */
    public static final AdminActionLog ADMIN_ACTION_LOG = AdminActionLog.ADMIN_ACTION_LOG;

    /**
     * The table <code>administrator</code>.
     */
    public static final Administrator ADMINISTRATOR = Administrator.ADMINISTRATOR;

    /**
     * The table <code>city</code>.
     */
    public static final City CITY = City.CITY;

    /**
     * The table <code>offer</code>.
     */
    public static final Offer OFFER = Offer.OFFER;

    /**
     * The table <code>profession</code>.
     */
    public static final Profession PROFESSION = Profession.PROFESSION;

    /**
     * The table <code>trader_details</code>.
     */
    public static final TraderDetails TRADER_DETAILS = TraderDetails.TRADER_DETAILS;

    /**
     * The table <code>trader_details_profession</code>.
     */
    public static final TraderDetailsProfession TRADER_DETAILS_PROFESSION = TraderDetailsProfession.TRADER_DETAILS_PROFESSION;

    /**
     * The table <code>user_details</code>.
     */
    public static final UserDetails USER_DETAILS = UserDetails.USER_DETAILS;
}
