/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.JSONB;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminActionLog implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       adminId;
    private String        actionType;
    private String        targetTable;
    private Integer       recordId;
    private JSONB         changeDetails;
    private LocalDateTime createdOn;

    public AdminActionLog() {}

    public AdminActionLog(AdminActionLog value) {
        this.id = value.id;
        this.adminId = value.adminId;
        this.actionType = value.actionType;
        this.targetTable = value.targetTable;
        this.recordId = value.recordId;
        this.changeDetails = value.changeDetails;
        this.createdOn = value.createdOn;
    }

    @ConstructorProperties({ "id", "adminId", "actionType", "targetTable", "recordId", "changeDetails", "createdOn" })
    public AdminActionLog(
        Integer       id,
        Integer       adminId,
        String        actionType,
        String        targetTable,
        Integer       recordId,
        JSONB         changeDetails,
        LocalDateTime createdOn
    ) {
        this.id = id;
        this.adminId = adminId;
        this.actionType = actionType;
        this.targetTable = targetTable;
        this.recordId = recordId;
        this.changeDetails = changeDetails;
        this.createdOn = createdOn;
    }

    /**
     * Getter for <code>admin_action_log.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>admin_action_log.id</code>.
     */
    public AdminActionLog setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.admin_id</code>.
     */
    public Integer getAdminId() {
        return this.adminId;
    }

    /**
     * Setter for <code>admin_action_log.admin_id</code>.
     */
    public AdminActionLog setAdminId(Integer adminId) {
        this.adminId = adminId;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.action_type</code>.
     */
    public String getActionType() {
        return this.actionType;
    }

    /**
     * Setter for <code>admin_action_log.action_type</code>.
     */
    public AdminActionLog setActionType(String actionType) {
        this.actionType = actionType;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.target_table</code>.
     */
    public String getTargetTable() {
        return this.targetTable;
    }

    /**
     * Setter for <code>admin_action_log.target_table</code>.
     */
    public AdminActionLog setTargetTable(String targetTable) {
        this.targetTable = targetTable;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.record_id</code>.
     */
    public Integer getRecordId() {
        return this.recordId;
    }

    /**
     * Setter for <code>admin_action_log.record_id</code>.
     */
    public AdminActionLog setRecordId(Integer recordId) {
        this.recordId = recordId;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.change_details</code>.
     */
    public JSONB getChangeDetails() {
        return this.changeDetails;
    }

    /**
     * Setter for <code>admin_action_log.change_details</code>.
     */
    public AdminActionLog setChangeDetails(JSONB changeDetails) {
        this.changeDetails = changeDetails;
        return this;
    }

    /**
     * Getter for <code>admin_action_log.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>admin_action_log.created_on</code>.
     */
    public AdminActionLog setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AdminActionLog other = (AdminActionLog) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (adminId == null) {
            if (other.adminId != null)
                return false;
        }
        else if (!adminId.equals(other.adminId))
            return false;
        if (actionType == null) {
            if (other.actionType != null)
                return false;
        }
        else if (!actionType.equals(other.actionType))
            return false;
        if (targetTable == null) {
            if (other.targetTable != null)
                return false;
        }
        else if (!targetTable.equals(other.targetTable))
            return false;
        if (recordId == null) {
            if (other.recordId != null)
                return false;
        }
        else if (!recordId.equals(other.recordId))
            return false;
        if (changeDetails == null) {
            if (other.changeDetails != null)
                return false;
        }
        else if (!changeDetails.equals(other.changeDetails))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.adminId == null) ? 0 : this.adminId.hashCode());
        result = prime * result + ((this.actionType == null) ? 0 : this.actionType.hashCode());
        result = prime * result + ((this.targetTable == null) ? 0 : this.targetTable.hashCode());
        result = prime * result + ((this.recordId == null) ? 0 : this.recordId.hashCode());
        result = prime * result + ((this.changeDetails == null) ? 0 : this.changeDetails.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AdminActionLog (");

        sb.append(id);
        sb.append(", ").append(adminId);
        sb.append(", ").append(actionType);
        sb.append(", ").append(targetTable);
        sb.append(", ").append(recordId);
        sb.append(", ").append(changeDetails);
        sb.append(", ").append(createdOn);

        sb.append(")");
        return sb.toString();
    }
}
