/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Administrator implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        username;
    private String        email;
    private String        password;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Administrator() {}

    public Administrator(Administrator value) {
        this.id = value.id;
        this.username = value.username;
        this.email = value.email;
        this.password = value.password;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "username", "email", "password", "createdOn", "updatedOn" })
    public Administrator(
        Integer       id,
        String        username,
        String        email,
        String        password,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.password = password;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>administrator.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>administrator.id</code>.
     */
    public Administrator setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>administrator.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>administrator.username</code>.
     */
    public Administrator setUsername(String username) {
        this.username = username;
        return this;
    }

    /**
     * Getter for <code>administrator.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>administrator.email</code>.
     */
    public Administrator setEmail(String email) {
        this.email = email;
        return this;
    }

    /**
     * Getter for <code>administrator.password</code>.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>administrator.password</code>.
     */
    public Administrator setPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Getter for <code>administrator.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>administrator.created_on</code>.
     */
    public Administrator setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>administrator.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>administrator.updated_on</code>.
     */
    public Administrator setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Administrator other = (Administrator) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (username == null) {
            if (other.username != null)
                return false;
        }
        else if (!username.equals(other.username))
            return false;
        if (email == null) {
            if (other.email != null)
                return false;
        }
        else if (!email.equals(other.email))
            return false;
        if (password == null) {
            if (other.password != null)
                return false;
        }
        else if (!password.equals(other.password))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Administrator (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(email);
        sb.append(", ").append(password);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
