/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        cityName;
    private String        status;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public City() {}

    public City(City value) {
        this.id = value.id;
        this.cityName = value.cityName;
        this.status = value.status;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "cityName", "status", "createdOn", "updatedOn" })
    public City(
        Integer       id,
        String        cityName,
        String        status,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.cityName = cityName;
        this.status = status;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>city.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>city.id</code>.
     */
    public City setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>city.city_name</code>.
     */
    public String getCityName() {
        return this.cityName;
    }

    /**
     * Setter for <code>city.city_name</code>.
     */
    public City setCityName(String cityName) {
        this.cityName = cityName;
        return this;
    }

    /**
     * Getter for <code>city.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>city.status</code>.
     */
    public City setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>city.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>city.created_on</code>.
     */
    public City setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>city.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>city.updated_on</code>.
     */
    public City setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final City other = (City) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (cityName == null) {
            if (other.cityName != null)
                return false;
        }
        else if (!cityName.equals(other.cityName))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.cityName == null) ? 0 : this.cityName.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("City (");

        sb.append(id);
        sb.append(", ").append(cityName);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
