/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Offer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       traderId;
    private Integer       professionId;
    private BigDecimal    pricePerUnit;
    private String        description;
    private BigDecimal    totalPrice;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Offer() {}

    public Offer(Offer value) {
        this.id = value.id;
        this.traderId = value.traderId;
        this.professionId = value.professionId;
        this.pricePerUnit = value.pricePerUnit;
        this.description = value.description;
        this.totalPrice = value.totalPrice;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "traderId", "professionId", "pricePerUnit", "description", "totalPrice", "createdOn", "updatedOn" })
    public Offer(
        Integer       id,
        Integer       traderId,
        Integer       professionId,
        BigDecimal    pricePerUnit,
        String        description,
        BigDecimal    totalPrice,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.traderId = traderId;
        this.professionId = professionId;
        this.pricePerUnit = pricePerUnit;
        this.description = description;
        this.totalPrice = totalPrice;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>offer.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>offer.id</code>.
     */
    public Offer setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>offer.trader_id</code>.
     */
    public Integer getTraderId() {
        return this.traderId;
    }

    /**
     * Setter for <code>offer.trader_id</code>.
     */
    public Offer setTraderId(Integer traderId) {
        this.traderId = traderId;
        return this;
    }

    /**
     * Getter for <code>offer.profession_id</code>.
     */
    public Integer getProfessionId() {
        return this.professionId;
    }

    /**
     * Setter for <code>offer.profession_id</code>.
     */
    public Offer setProfessionId(Integer professionId) {
        this.professionId = professionId;
        return this;
    }

    /**
     * Getter for <code>offer.price_per_unit</code>.
     */
    public BigDecimal getPricePerUnit() {
        return this.pricePerUnit;
    }

    /**
     * Setter for <code>offer.price_per_unit</code>.
     */
    public Offer setPricePerUnit(BigDecimal pricePerUnit) {
        this.pricePerUnit = pricePerUnit;
        return this;
    }

    /**
     * Getter for <code>offer.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>offer.description</code>.
     */
    public Offer setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>offer.total_price</code>.
     */
    public BigDecimal getTotalPrice() {
        return this.totalPrice;
    }

    /**
     * Setter for <code>offer.total_price</code>.
     */
    public Offer setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
        return this;
    }

    /**
     * Getter for <code>offer.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>offer.created_on</code>.
     */
    public Offer setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>offer.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>offer.updated_on</code>.
     */
    public Offer setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Offer other = (Offer) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (traderId == null) {
            if (other.traderId != null)
                return false;
        }
        else if (!traderId.equals(other.traderId))
            return false;
        if (professionId == null) {
            if (other.professionId != null)
                return false;
        }
        else if (!professionId.equals(other.professionId))
            return false;
        if (pricePerUnit == null) {
            if (other.pricePerUnit != null)
                return false;
        }
        else if (!pricePerUnit.equals(other.pricePerUnit))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (totalPrice == null) {
            if (other.totalPrice != null)
                return false;
        }
        else if (!totalPrice.equals(other.totalPrice))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.traderId == null) ? 0 : this.traderId.hashCode());
        result = prime * result + ((this.professionId == null) ? 0 : this.professionId.hashCode());
        result = prime * result + ((this.pricePerUnit == null) ? 0 : this.pricePerUnit.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.totalPrice == null) ? 0 : this.totalPrice.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Offer (");

        sb.append(id);
        sb.append(", ").append(traderId);
        sb.append(", ").append(professionId);
        sb.append(", ").append(pricePerUnit);
        sb.append(", ").append(description);
        sb.append(", ").append(totalPrice);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
