/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Offer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       traderId;
    private Integer       cityId;
    private Integer       professionId;
    private String        priceUnit;
    private BigDecimal    wagePerPriceUnit;
    private String        description;
    private String        status;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Offer() {}

    public Offer(Offer value) {
        this.id = value.id;
        this.traderId = value.traderId;
        this.cityId = value.cityId;
        this.professionId = value.professionId;
        this.priceUnit = value.priceUnit;
        this.wagePerPriceUnit = value.wagePerPriceUnit;
        this.description = value.description;
        this.status = value.status;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "traderId", "cityId", "professionId", "priceUnit", "wagePerPriceUnit", "description", "status", "createdOn", "updatedOn" })
    public Offer(
        Integer       id,
        Integer       traderId,
        Integer       cityId,
        Integer       professionId,
        String        priceUnit,
        BigDecimal    wagePerPriceUnit,
        String        description,
        String        status,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.traderId = traderId;
        this.cityId = cityId;
        this.professionId = professionId;
        this.priceUnit = priceUnit;
        this.wagePerPriceUnit = wagePerPriceUnit;
        this.description = description;
        this.status = status;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>offer.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>offer.id</code>.
     */
    public Offer setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>offer.trader_id</code>.
     */
    public Integer getTraderId() {
        return this.traderId;
    }

    /**
     * Setter for <code>offer.trader_id</code>.
     */
    public Offer setTraderId(Integer traderId) {
        this.traderId = traderId;
        return this;
    }

    /**
     * Getter for <code>offer.city_id</code>.
     */
    public Integer getCityId() {
        return this.cityId;
    }

    /**
     * Setter for <code>offer.city_id</code>.
     */
    public Offer setCityId(Integer cityId) {
        this.cityId = cityId;
        return this;
    }

    /**
     * Getter for <code>offer.profession_id</code>.
     */
    public Integer getProfessionId() {
        return this.professionId;
    }

    /**
     * Setter for <code>offer.profession_id</code>.
     */
    public Offer setProfessionId(Integer professionId) {
        this.professionId = professionId;
        return this;
    }

    /**
     * Getter for <code>offer.price_unit</code>.
     */
    public String getPriceUnit() {
        return this.priceUnit;
    }

    /**
     * Setter for <code>offer.price_unit</code>.
     */
    public Offer setPriceUnit(String priceUnit) {
        this.priceUnit = priceUnit;
        return this;
    }

    /**
     * Getter for <code>offer.wage_per_price_unit</code>.
     */
    public BigDecimal getWagePerPriceUnit() {
        return this.wagePerPriceUnit;
    }

    /**
     * Setter for <code>offer.wage_per_price_unit</code>.
     */
    public Offer setWagePerPriceUnit(BigDecimal wagePerPriceUnit) {
        this.wagePerPriceUnit = wagePerPriceUnit;
        return this;
    }

    /**
     * Getter for <code>offer.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>offer.description</code>.
     */
    public Offer setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>offer.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>offer.status</code>.
     */
    public Offer setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>offer.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>offer.created_on</code>.
     */
    public Offer setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>offer.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>offer.updated_on</code>.
     */
    public Offer setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Offer other = (Offer) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (traderId == null) {
            if (other.traderId != null)
                return false;
        }
        else if (!traderId.equals(other.traderId))
            return false;
        if (cityId == null) {
            if (other.cityId != null)
                return false;
        }
        else if (!cityId.equals(other.cityId))
            return false;
        if (professionId == null) {
            if (other.professionId != null)
                return false;
        }
        else if (!professionId.equals(other.professionId))
            return false;
        if (priceUnit == null) {
            if (other.priceUnit != null)
                return false;
        }
        else if (!priceUnit.equals(other.priceUnit))
            return false;
        if (wagePerPriceUnit == null) {
            if (other.wagePerPriceUnit != null)
                return false;
        }
        else if (!wagePerPriceUnit.equals(other.wagePerPriceUnit))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.traderId == null) ? 0 : this.traderId.hashCode());
        result = prime * result + ((this.cityId == null) ? 0 : this.cityId.hashCode());
        result = prime * result + ((this.professionId == null) ? 0 : this.professionId.hashCode());
        result = prime * result + ((this.priceUnit == null) ? 0 : this.priceUnit.hashCode());
        result = prime * result + ((this.wagePerPriceUnit == null) ? 0 : this.wagePerPriceUnit.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Offer (");

        sb.append(id);
        sb.append(", ").append(traderId);
        sb.append(", ").append(cityId);
        sb.append(", ").append(professionId);
        sb.append(", ").append(priceUnit);
        sb.append(", ").append(wagePerPriceUnit);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
