/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OfferResource implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       offerId;
    private Integer       resourceId;
    private BigDecimal    quantity;
    private BigDecimal    unitPrice;
    private BigDecimal    totalCost;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public OfferResource() {}

    public OfferResource(OfferResource value) {
        this.id = value.id;
        this.offerId = value.offerId;
        this.resourceId = value.resourceId;
        this.quantity = value.quantity;
        this.unitPrice = value.unitPrice;
        this.totalCost = value.totalCost;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "offerId", "resourceId", "quantity", "unitPrice", "totalCost", "createdOn", "updatedOn" })
    public OfferResource(
        Integer       id,
        Integer       offerId,
        Integer       resourceId,
        BigDecimal    quantity,
        BigDecimal    unitPrice,
        BigDecimal    totalCost,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.offerId = offerId;
        this.resourceId = resourceId;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.totalCost = totalCost;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>offer_resource.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>offer_resource.id</code>.
     */
    public OfferResource setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>offer_resource.offer_id</code>.
     */
    public Integer getOfferId() {
        return this.offerId;
    }

    /**
     * Setter for <code>offer_resource.offer_id</code>.
     */
    public OfferResource setOfferId(Integer offerId) {
        this.offerId = offerId;
        return this;
    }

    /**
     * Getter for <code>offer_resource.resource_id</code>.
     */
    public Integer getResourceId() {
        return this.resourceId;
    }

    /**
     * Setter for <code>offer_resource.resource_id</code>.
     */
    public OfferResource setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
        return this;
    }

    /**
     * Getter for <code>offer_resource.quantity</code>.
     */
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    /**
     * Setter for <code>offer_resource.quantity</code>.
     */
    public OfferResource setQuantity(BigDecimal quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Getter for <code>offer_resource.unit_price</code>.
     */
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }

    /**
     * Setter for <code>offer_resource.unit_price</code>.
     */
    public OfferResource setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
        return this;
    }

    /**
     * Getter for <code>offer_resource.total_cost</code>.
     */
    public BigDecimal getTotalCost() {
        return this.totalCost;
    }

    /**
     * Setter for <code>offer_resource.total_cost</code>.
     */
    public OfferResource setTotalCost(BigDecimal totalCost) {
        this.totalCost = totalCost;
        return this;
    }

    /**
     * Getter for <code>offer_resource.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>offer_resource.created_on</code>.
     */
    public OfferResource setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>offer_resource.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>offer_resource.updated_on</code>.
     */
    public OfferResource setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OfferResource other = (OfferResource) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (offerId == null) {
            if (other.offerId != null)
                return false;
        }
        else if (!offerId.equals(other.offerId))
            return false;
        if (resourceId == null) {
            if (other.resourceId != null)
                return false;
        }
        else if (!resourceId.equals(other.resourceId))
            return false;
        if (quantity == null) {
            if (other.quantity != null)
                return false;
        }
        else if (!quantity.equals(other.quantity))
            return false;
        if (unitPrice == null) {
            if (other.unitPrice != null)
                return false;
        }
        else if (!unitPrice.equals(other.unitPrice))
            return false;
        if (totalCost == null) {
            if (other.totalCost != null)
                return false;
        }
        else if (!totalCost.equals(other.totalCost))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.offerId == null) ? 0 : this.offerId.hashCode());
        result = prime * result + ((this.resourceId == null) ? 0 : this.resourceId.hashCode());
        result = prime * result + ((this.quantity == null) ? 0 : this.quantity.hashCode());
        result = prime * result + ((this.unitPrice == null) ? 0 : this.unitPrice.hashCode());
        result = prime * result + ((this.totalCost == null) ? 0 : this.totalCost.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OfferResource (");

        sb.append(id);
        sb.append(", ").append(offerId);
        sb.append(", ").append(resourceId);
        sb.append(", ").append(quantity);
        sb.append(", ").append(unitPrice);
        sb.append(", ").append(totalCost);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
