/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profession implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private String        professionName;
    private String        description;
    private String        status;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public Profession() {}

    public Profession(Profession value) {
        this.id = value.id;
        this.professionName = value.professionName;
        this.description = value.description;
        this.status = value.status;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "professionName", "description", "status", "createdOn", "updatedOn" })
    public Profession(
        Integer       id,
        String        professionName,
        String        description,
        String        status,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.professionName = professionName;
        this.description = description;
        this.status = status;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>profession.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>profession.id</code>.
     */
    public Profession setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>profession.profession_name</code>.
     */
    public String getProfessionName() {
        return this.professionName;
    }

    /**
     * Setter for <code>profession.profession_name</code>.
     */
    public Profession setProfessionName(String professionName) {
        this.professionName = professionName;
        return this;
    }

    /**
     * Getter for <code>profession.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>profession.description</code>.
     */
    public Profession setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>profession.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>profession.status</code>.
     */
    public Profession setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>profession.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>profession.created_on</code>.
     */
    public Profession setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>profession.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>profession.updated_on</code>.
     */
    public Profession setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Profession other = (Profession) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (professionName == null) {
            if (other.professionName != null)
                return false;
        }
        else if (!professionName.equals(other.professionName))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.professionName == null) ? 0 : this.professionName.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Profession (");

        sb.append(id);
        sb.append(", ").append(professionName);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
