/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraderDetailsProfession implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       traderId;
    private Integer       professionId;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public TraderDetailsProfession() {}

    public TraderDetailsProfession(TraderDetailsProfession value) {
        this.traderId = value.traderId;
        this.professionId = value.professionId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "traderId", "professionId", "createdOn", "updatedOn" })
    public TraderDetailsProfession(
        Integer       traderId,
        Integer       professionId,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.traderId = traderId;
        this.professionId = professionId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>trader_details_profession.trader_id</code>.
     */
    public Integer getTraderId() {
        return this.traderId;
    }

    /**
     * Setter for <code>trader_details_profession.trader_id</code>.
     */
    public TraderDetailsProfession setTraderId(Integer traderId) {
        this.traderId = traderId;
        return this;
    }

    /**
     * Getter for <code>trader_details_profession.profession_id</code>.
     */
    public Integer getProfessionId() {
        return this.professionId;
    }

    /**
     * Setter for <code>trader_details_profession.profession_id</code>.
     */
    public TraderDetailsProfession setProfessionId(Integer professionId) {
        this.professionId = professionId;
        return this;
    }

    /**
     * Getter for <code>trader_details_profession.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>trader_details_profession.created_on</code>.
     */
    public TraderDetailsProfession setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>trader_details_profession.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>trader_details_profession.updated_on</code>.
     */
    public TraderDetailsProfession setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TraderDetailsProfession other = (TraderDetailsProfession) obj;
        if (traderId == null) {
            if (other.traderId != null)
                return false;
        }
        else if (!traderId.equals(other.traderId))
            return false;
        if (professionId == null) {
            if (other.professionId != null)
                return false;
        }
        else if (!professionId.equals(other.professionId))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.traderId == null) ? 0 : this.traderId.hashCode());
        result = prime * result + ((this.professionId == null) ? 0 : this.professionId.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TraderDetailsProfession (");

        sb.append(traderId);
        sb.append(", ").append(professionId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
