/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraderDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer id;
    private Integer userId;
    private Integer professionId;
    private String  mobileNumber;
    private String  description;

    public TraderDetails() {}

    public TraderDetails(TraderDetails value) {
        this.id = value.id;
        this.userId = value.userId;
        this.professionId = value.professionId;
        this.mobileNumber = value.mobileNumber;
        this.description = value.description;
    }

    @ConstructorProperties({ "id", "userId", "professionId", "mobileNumber", "description" })
    public TraderDetails(
        Integer id,
        Integer userId,
        Integer professionId,
        String  mobileNumber,
        String  description
    ) {
        this.id = id;
        this.userId = userId;
        this.professionId = professionId;
        this.mobileNumber = mobileNumber;
        this.description = description;
    }

    /**
     * Getter for <code>trader_details.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>trader_details.id</code>.
     */
    public TraderDetails setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>trader_details.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>trader_details.user_id</code>.
     */
    public TraderDetails setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>trader_details.profession_id</code>.
     */
    public Integer getProfessionId() {
        return this.professionId;
    }

    /**
     * Setter for <code>trader_details.profession_id</code>.
     */
    public TraderDetails setProfessionId(Integer professionId) {
        this.professionId = professionId;
        return this;
    }

    /**
     * Getter for <code>trader_details.mobile_number</code>.
     */
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    /**
     * Setter for <code>trader_details.mobile_number</code>.
     */
    public TraderDetails setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    /**
     * Getter for <code>trader_details.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>trader_details.description</code>.
     */
    public TraderDetails setDescription(String description) {
        this.description = description;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TraderDetails other = (TraderDetails) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (professionId == null) {
            if (other.professionId != null)
                return false;
        }
        else if (!professionId.equals(other.professionId))
            return false;
        if (mobileNumber == null) {
            if (other.mobileNumber != null)
                return false;
        }
        else if (!mobileNumber.equals(other.mobileNumber))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.professionId == null) ? 0 : this.professionId.hashCode());
        result = prime * result + ((this.mobileNumber == null) ? 0 : this.mobileNumber.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TraderDetails (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(professionId);
        sb.append(", ").append(mobileNumber);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
