/*
 * This file is generated by jOOQ.
 */
package com.dreamjob.db.jooq.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.16.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TraderDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer       id;
    private Integer       userId;
    private String        mobileNumber;
    private String        description;
    private String        status;
    private LocalDateTime createdOn;
    private LocalDateTime updatedOn;

    public TraderDetails() {}

    public TraderDetails(TraderDetails value) {
        this.id = value.id;
        this.userId = value.userId;
        this.mobileNumber = value.mobileNumber;
        this.description = value.description;
        this.status = value.status;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
    }

    @ConstructorProperties({ "id", "userId", "mobileNumber", "description", "status", "createdOn", "updatedOn" })
    public TraderDetails(
        Integer       id,
        Integer       userId,
        String        mobileNumber,
        String        description,
        String        status,
        LocalDateTime createdOn,
        LocalDateTime updatedOn
    ) {
        this.id = id;
        this.userId = userId;
        this.mobileNumber = mobileNumber;
        this.description = description;
        this.status = status;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
    }

    /**
     * Getter for <code>trader_details.id</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>trader_details.id</code>.
     */
    public TraderDetails setId(Integer id) {
        this.id = id;
        return this;
    }

    /**
     * Getter for <code>trader_details.user_id</code>.
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>trader_details.user_id</code>.
     */
    public TraderDetails setUserId(Integer userId) {
        this.userId = userId;
        return this;
    }

    /**
     * Getter for <code>trader_details.mobile_number</code>.
     */
    public String getMobileNumber() {
        return this.mobileNumber;
    }

    /**
     * Setter for <code>trader_details.mobile_number</code>.
     */
    public TraderDetails setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
        return this;
    }

    /**
     * Getter for <code>trader_details.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>trader_details.description</code>.
     */
    public TraderDetails setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Getter for <code>trader_details.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>trader_details.status</code>.
     */
    public TraderDetails setStatus(String status) {
        this.status = status;
        return this;
    }

    /**
     * Getter for <code>trader_details.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return this.createdOn;
    }

    /**
     * Setter for <code>trader_details.created_on</code>.
     */
    public TraderDetails setCreatedOn(LocalDateTime createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    /**
     * Getter for <code>trader_details.updated_on</code>.
     */
    public LocalDateTime getUpdatedOn() {
        return this.updatedOn;
    }

    /**
     * Setter for <code>trader_details.updated_on</code>.
     */
    public TraderDetails setUpdatedOn(LocalDateTime updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final TraderDetails other = (TraderDetails) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (mobileNumber == null) {
            if (other.mobileNumber != null)
                return false;
        }
        else if (!mobileNumber.equals(other.mobileNumber))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.mobileNumber == null) ? 0 : this.mobileNumber.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        result = prime * result + ((this.createdOn == null) ? 0 : this.createdOn.hashCode());
        result = prime * result + ((this.updatedOn == null) ? 0 : this.updatedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TraderDetails (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(mobileNumber);
        sb.append(", ").append(description);
        sb.append(", ").append(status);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);

        sb.append(")");
        return sb.toString();
    }
}
